// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  /** TheTVDB API KEY */
  THE_TVDB_API_KEY: string
  /** TMDB API KEY */
  TMDB_API_KEY: string
  /** 是否开启缓存 */
  CACHE: boolean
}
